apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "common.names.fullname" . }}-node
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app: hcloud-csi
spec:
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app: hcloud-csi
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app: hcloud-csi
    spec:
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: instance.hetzner.cloud/is-root-server
                  operator: NotIn
                  values:
                    - "true"
      containers:
        - name: csi-node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0
          args:
            - --kubelet-registration-path={{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins/csi.hetzner.cloud/socket
          volumeMounts:
            - name: plugin-dir
              mountPath: /run/csi
            - name: registration-dir
              mountPath: /registration
        - name: hcloud-csi-driver
          image: {{ .Values.node.image }}:{{ .Values.node.tag }}
          imagePullPolicy: {{ .Values.node.imagePullPolicy | default "IfNotPresent" }}
          command:
            - /bin/hcloud-csi-driver-node
          env:
            - name: CSI_ENDPOINT
              value: unix:///run/csi/socket
            - name: METRICS_ENDPOINT
              value: 0.0.0.0:9189
            - name: ENABLE_METRICS
              value: "{{ .Values.metrics.enabled }}"
          volumeMounts:
            - name: kubelet-dir
              mountPath: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /run/csi
            - name: device-dir
              mountPath: /dev
          securityContext:
            privileged: true
          ports:
            {{- if .Values.metrics.enabled }}
            - containerPort: 9189
              name: metrics
            {{- end }}
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.9.0
          imagePullPolicy: {{ .Values.node.imagePullPolicy | default "IfNotPresent" }}
          volumeMounts:
            - mountPath: /run/csi
              name: plugin-dir
      volumes:
        - name: kubelet-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins/csi.hetzner.cloud/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins_registry/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
