{{- if .Values.EncryptedStorageClass.encryptionpassphrase }}
apiVersion: v1
kind: Secret
metadata:
 name: encryption-secret
 namespace: kube-system
stringData:
 encryption-passphrase: {{ .Values.EncryptedStorageClass.encryptionpassphrase }}
{{- end }}
