apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.storageClass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: csi.hetzner.cloud
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy | default "Delete" }}
---
{{- if .Values.EncryptedStorageClass.encryptionpassphrase }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.EncryptedStorageClass.name }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.EncryptedStorageClass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: csi.hetzner.cloud
volumeBindingMode: {{ .Values.EncryptedStorageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.EncryptedStorageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.EncryptedStorageClass.reclaimPolicy | default "Delete" }}
parameters:
  csi.storage.k8s.io/node-publish-secret-name: encryption-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
{{- end }}
