{{- if .Values.hcloud_token }}
apiVersion: v1
data:
  token: {{ .Values.hcloud_token | b64enc }}
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
type: Opaque
{{- end }}
{{- if .Values.hcsi_encryption_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-secret
  namespace: kube-system
stringData:
  encryption-passphrase: {{ .Values.hcsi_encryption_key }}
{{- end }}
